version: "3"

services:
  postgres:
    image: postgres:alpine
    environment:
      - POSTGRES_PASSWORD=password
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./scripts:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
    restart: unless-stopped

  adminer:
    image: adminer
    ports:
      - 8080:8080
    restart: unless-stopped

