version: "3"

services:
  postgres:
    image: postgres:alpine
    environment:
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres-vol:/var/lib/postgresql/data:rw
      - ./postgres/scripts:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
    restart: unless-stopped

  adminer:
    image: adminer
    ports:
      - 8080:8080
    restart: unless-stopped

volumes:
  postgres-vol:
